Play travis
Otus-DevOps-2021-05/NoBodySargon_infra pull request #1
Opened 2021-06-14 16:37 UTC by NoBodySargon

Ok, all done?

2021-06-14 17:36 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил комментарий к файлу, дз возвращаю на доработку.

2021-06-14 17:36 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Обратите внимание на этот файл =)

2021-06-15 07:39 UTC, NoBodySargon commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Нашел ошибку, исправил.

2021-06-15 11:53 UTC, NoBodySargon reviewed
Внесены изменеия в листинге test.py
(исправлена функция проверки )

2021-06-15 12:06 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-06-15 20:36 UTC, merged